### Login para obter access e refresh tokens
POST http://127.0.0.1:8000/auth/login HTTP/1.1
content-type: application/json

{
    "cpf" : "1",
    "senha" : "abcBolinhas"
}

### token gerado
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjEsImdydXBvIjoxLCJleHAiOjE3NzYxMjMyMjAsInR5cGUiOiJhY2Nlc3MifQ.AMhuC5hMStQ06ZLuj3ic1K4TEDi4qcypao-0cEJWIT8
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjEsImdydXBvIjoxLCJleHAiOjE3NzY2OTIwMjAsInR5cGUiOiJyZWZyZXNoIn0.Ul2ldF-AyQSHSQaCxy9lV9MUv69HdqyzSWDIeRQoElw

@access_token_LoginAuditoria = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaWQiOjIsImdydXBvIjoyLCJleHAiOjE3NzU2NTM3ODMsInR5cGUiOiJhY2Nlc3MifQ.XFux4A8PZ-j5LgyxFNgQWlAqYNAiBiWUcMtraFhBvLA

@refresh_token_LoginAuditoria = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaWQiOjIsImdydXBvIjoyLCJleHAiOjE3NzYyNTc2ODMsInR5cGUiOiJyZWZyZXNoIn0.Jq1zrd2KTybn-gRDzmNhZ2sp26y6lo6Ht_h7B31pZM8
### testar access token para acessar endpoint protegido
GET http://127.0.0.1:8000/auth/me HTTP/1.1
Authorization: Bearer {{access_token_LoginAuditoria}}

### Usar refresh token para obter novos tokens
POST http://localhost:8000/auth/refresh
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

# access novo do admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjEsImdydXBvIjoxLCJleHAiOjE3NzQ3MjYwNDYsInR5cGUiOiJhY2Nlc3MifQ.VNUr7vgosrll9c3paBDJslFL-pwEu1eQUzmeQ4QH_N8
# refresh novo do admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjEsImdydXBvIjoxLCJleHAiOjE3NzUzMjk5NDYsInR5cGUiOiJyZWZyZXNoIn0.aFuqDE-uwMXowZEqtqVq3ElO78vqRrP6B0u7GL5-sCI